### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by hugsbrugs** [JumpLink/angular-toggle-switch#16]
Hi ! 

On this page : http://jumplink.github.io/angular-toggle-switch/

Bower install link : 
bower install angular-toggle-switch --save 
refers to another similar plugin : https://github.com/cgarvis/angular-toggle-switch

You should replace it with the correct one : 
bower install angular-bootstrap-toggle-switch --save

**Comment by JumpLink** [comment]
thank you, fixed!

**Comment by xuchen** [comment]
Took me a while to figure out why mine wasn't *looking like* it was working: the docs didn't say that I had to include "angular-toggle-switch-bootstrap-3.css" too!
