### ISSUE TITLE
second button error

### ISSUE THREAD

**Issue by html5developer-mumtaz** [JumpLink/angular-toggle-switch#36]
![](https://cloud.githubusercontent.com/assets/1139967/21422647/a4536fca-c85e-11e6-8856-0f20bce71509.png)

![](https://cloud.githubusercontent.com/assets/1139967/21422660/ad4ac416-c85e-11e6-8bef-e226bd17c5d9.png)
second button error

**Comment by darkguy2008** [comment]
Please answer in the other bug, you haven't answered there yet.

**Comment by darkguy2008** [comment]
Related to #35
