### ISSUE TITLE
isDisabled

### ISSUE THREAD

**Issue by sgentile** [JumpLink/angular-toggle-switch#6]
I'm using your forked version for support of 'isDisabled' - 

I've tried 
```html
<toggle-switch is-disabled="disabled" ...>
    </toggle-switch>
```

and 

```html
<toggle-switch is-disabled="true" ...>
    </toggle-switch>
```
Neither seem to work - the demo page doesn't appear to disabled it either ?

**Comment by Gary-Li** [comment]
The latest version isn't support ng-disabled directive anymore.

**Comment by JumpLink** [comment]
I've update the demo page and released a new version, is it now working for you @sgentile?
