### ISSUE TITLE
Styles for sizes and colors are missing from the package

### ISSUE THREAD

**Issue by sorgoz** [JumpLink/angular-toggle-switch#8]
When I tried to set size of the switch to different than default, I found there is no CSS specs for classes described on the demo page.

```
<toggle-switch ng-model="onPause" class="switch-success switch-mini"><toggle-switch>
```

Both "switch-success" and "switch-mini" (and others) are missing from css files in the bower package.

The demo page also says the model attribute is named as "model" while this throws exception. The right attr name should be "ng-model".

**Comment by JumpLink** [comment]
You can find the css specs you are looking for in https://github.com/JumpLink/angular-toggle-switch/blob/master/style/bootstrap3/angular-toggle-switch-bootstrap-3.css#L175

**Comment by JumpLink** [comment]
I think you are installed the [angular-toggle-switch from cgarvis](https://github.com/cgarvis/angular-toggle-switch) this project is forked from.

**Comment by jmayday** [comment]
I did the same mistake. Is your directive available as NPM package?
